### ISSUE TITLE
idea for a more useful acme-client

### ISSUE THREAD

**Issue by hdatma** [graywolf/acme-client-portable#3]
WHAT
Focus on ACMEv2 with DNS ACME challenge only
Deprecate ACMEv1
Deprecate HTTP ACME challenge

WHY
HTTP challenge: fails when rescuing an HTTPS only system from an expired certificate
Wildcard certificates: require DNS challenge
Overall: leaner code, focused on what matters

**Comment by graywolf** [comment]
Focus of this project is just to provide version of openbsd's acme-client capable of running on other systems (main interested being linux), so I do not intent to add any features. Feel free to propose this to them ( https://www.openbsd.org/mail.html ).
