### ISSUE TITLE
compat.c fails to build on Debian 8

### ISSUE THREAD

**Issue by mherrb** [graywolf/acme-client-portable#4]
I'm trying to build acme-client-portable on Debian 8. It fails with:
<pre>
gcc -std=gnu99 -DHAVE_CONFIG_H -I.    -D_GNU_SOURCE=1 -Wall -Werror -Wextra -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wshadow -Wsign-compare -Wstrict-prototypes -Wundef -Wunused -flto -I/usr/local/include  -g -O2 -MT compat.o -MD -MP -MF .deps/compat.Tpo -c -o compat.o compat.c
compat.c: In function ‘recallocarray’:
compat.c:22:2: error: implicit declaration of function ‘__builtin_mul_overflow’ [-Werror=implicit-function-declaration]
  if (__builtin_mul_overflow(oldnmemb, size, &bytes)) {
  ^
cc1: all warnings being treated as errors
Makefile:505: recipe for target 'compat.o' failed
make[1]: *** [compat.o] Error 1
make[1]: Leaving directory '/usr/local/src/acme-client-portable'
Makefile:379: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

The solution is probably to use the reallocarray() implementation from OpenBSD:
https://github.com/openbsd/src/blob/master/lib/libc/stdlib/reallocarray.c

**Comment by mherrb** [comment]
I mean https://github.com/openbsd/src/blob/master/lib/libc/stdlib/recallocarray.c

**Comment by graywolf** [comment]
Thx for bug report, should be fixed in 20f6ee489759bab3c48642284f27f0bafabf8912. Let me know if it works.

**Comment by graywolf** [comment]
Please try 5dc8cbd96c6ea4160ad85a7eeed73505600e410d (or just current master) instead. There was another issue in debian. I really need to setup automated building :)

**Comment by mherrb** [comment]
Hi,
Thanks for the quick fixes. I confirm that It now builds for me on Debian 8.
